# PYTORCH

WHAT IS PYTORCH?

- It’s a Python-based scientific computing package targeted at two sets of 
audiences:


- A replacement for NumPy to use the power of GPUs
a deep learning research platform that provides maximum flexibility 
and speed


In [1]:
from __future__ import print_function
import torch

## Tensors :
are similar to Numpy's ndarrays, with the addion being that Tensors can also be used on a GPU  accelerate computing

In [7]:
#Construct a 5*3 matrix, uninitialized
x = torch.empty(5,2)
print(x)

tensor([[0.0002, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [   nan,    nan],
        [0.0000, 0.0000]])


In [8]:
#construct a randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.9022, 0.2460, 0.7793],
        [0.5753, 0.5323, 0.2901],
        [0.6590, 0.2090, 0.7277],
        [0.6765, 0.4330, 0.9287],
        [0.7294, 0.9931, 0.5188]])


In [12]:
#Construct a matix filled zeros and of dtype long
x = torch.zeros(5,3,dtype=torch.long)
print(x)
type(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


torch.Tensor

In [11]:
#Construct a tensor directly from data:
x = torch.tensor([5.5,3])
print(x)
type(x)

tensor([5.5000, 3.0000])


torch.Tensor

In [14]:
x = x.new_ones(5,3,dtype=torch.double)  # new_*methods take in sizes
print(x)
#type(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [16]:
x = torch.rand_like(x,dtype=torch.float) # override dtype!
print(x)                          #here result has the same size

tensor([[0.0193, 0.0238, 0.3067],
        [0.7675, 0.4631, 0.7700],
        [0.9006, 0.0482, 0.2655],
        [0.5588, 0.3542, 0.7828],
        [0.3831, 0.3664, 0.3332]])


In [18]:
#Get its size
print(x.size())

#torch.Size is fact a tuple, so it supports all tuple operations.

torch.Size([5, 3])


# Operations


In [25]:
#Addition
y = torch.rand(5,3)
z = torch.ones(5,3)
print(x+y+z)

tensor([[1.8116, 1.9881, 1.5663],
        [2.3635, 2.4501, 2.3199],
        [2.0639, 1.0690, 1.8914],
        [1.9212, 1.3875, 1.8249],
        [1.5138, 1.9461, 1.4641]])


In [27]:
#Addition: syntax 2
print(torch.add(x,z))

tensor([[1.0193, 1.0238, 1.3067],
        [1.7675, 1.4631, 1.7700],
        [1.9006, 1.0482, 1.2655],
        [1.5588, 1.3542, 1.7828],
        [1.3831, 1.3664, 1.3332]])


In [31]:
#Addition: providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)


tensor([[0.8116, 0.9881, 0.5663],
        [1.3635, 1.4501, 1.3199],
        [1.0639, 0.0690, 0.8914],
        [0.9212, 0.3875, 0.8249],
        [0.5138, 0.9461, 0.4641]])


In [33]:
#Addition in-place
#adds x to y
y.add(x)
print(y)



tensor([[0.7922, 0.9643, 0.2596],
        [0.5960, 0.9870, 0.5499],
        [0.1633, 0.0207, 0.6259],
        [0.3624, 0.0333, 0.0420],
        [0.1307, 0.5797, 0.1309]])


In [35]:
#Any operation that mutates a tensor in-place is post-fixed with an _.
#For example: x.copy_(y), x.t_(), will change x.

In [37]:
#You cna use Numpy like indexing with all bells and whistles!
print(x)
print(x[:1])


tensor([[0.0193, 0.0238, 0.3067],
        [0.7675, 0.4631, 0.7700],
        [0.9006, 0.0482, 0.2655],
        [0.5588, 0.3542, 0.7828],
        [0.3831, 0.3664, 0.3332]])
tensor([[0.0193, 0.0238, 0.3067]])


In [62]:
#Resizing : If you want to resize/reshape tensor, you can use torch.view

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,) # the size -1 is inferred from other dimesions
print(x.size(),y.size(),z.size())
print(x)
print(y)



torch.Size([4, 4]) torch.Size([16]) torch.Size([16])
tensor([[ 0.6953, -2.2587,  1.5000, -1.1908],
        [-0.7109,  2.5718,  0.1389,  2.3503],
        [ 2.5763, -1.1891,  0.0916,  0.1597],
        [ 0.3511,  2.6366,  0.6165, -1.0908]])
tensor([ 0.6953, -2.2587,  1.5000, -1.1908, -0.7109,  2.5718,  0.1389,  2.3503,
         2.5763, -1.1891,  0.0916,  0.1597,  0.3511,  2.6366,  0.6165, -1.0908])


In [63]:
print(y.dim())
z.dim()
print(z)


1
tensor([ 0.6953, -2.2587,  1.5000, -1.1908, -0.7109,  2.5718,  0.1389,  2.3503,
         2.5763, -1.1891,  0.0916,  0.1597,  0.3511,  2.6366,  0.6165, -1.0908])


In [64]:
# If you have a one element tensor, use .item() to get the value as a Python
#number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0490])
-0.04903619363903999


###  Read later 100+ Tensor operations, including transposing,indexing,slicing,mathematical operations, linear algebra, random numbers,etc., are present.


In [66]:
#Numpy Bridge
#converting a torch tensor to Numpy array and vice-versa


In [70]:
a = torch.ones(5)
print(a)
type(a)

tensor([1., 1., 1., 1., 1.])


torch.Tensor

In [69]:
b = a.numpy()
print(b)
type(b)

[ 1.  1.  1.  1.  1.]


numpy.ndarray

In [77]:
# How numpy array changed in value
a.add_(1)
print (a)
print (b)

tensor([8., 8., 8., 8., 8.])
[ 1.  1.  1.  1.  1.]


In [80]:
#Converting Numpy array to torch tensor

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [81]:
#CUDA TENSORS
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


tensor([0.9510], device='cuda:0')
tensor([0.9510], dtype=torch.float64)
